services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    command:
      - "--http-api-update"
    ports:
      - "8080:8080"
    environment:
      - "WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}"
      - "WATCHTOWER_SCHEDULE=0 0 1 * * 2"
      - "WATCHTOWER_HTTP_API_METRICS=true"
      - "WATCHTOWER_NOTIFICATION_URL=${DISCORD_URL}"
      - "WATCHTOWER_CLEANUP=true"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro